### ISSUE TITLE
Xcell fails on LM9 matrix

### ISSUE THREAD

**Issue by sgosline** [sgosline/proteomicsTumorDeconv#84]
I cannot get xcell to run. To reproduce this error:

```
cwltool call-deconv-and-cor.cwl --cancerType [any cancer type] --mrna-alg xcell --prot-alg xcell --signature ../signature_matrices/LM9.txt --tissueType [normal|tumor]
```
I'm not sure what is going wrong, but the algorihtm fails on the file format.

**Comment by LifeWorks** [comment]
I am evaluating the bug now. Will put up the updates later

**Comment by LifeWorks** [comment]
After hours of battling with the pipeline and xcell source code, I finally find the reason for the bug now. Because of transforming the signature matrix into lists. One cell type has no marker gene, which returns a score table with only 8 cell types, when scaling the table it accesses the rows with all cell types. Then the error occurred and deconvolued table will not be generate properly. I will make a quick fix on it.
